work

diff --git a/.github/workflows/terraform-apply.yaml b/.github/workflows/terraform-apply.yaml
--- a/.github/workflows/terraform-apply.yaml
+++ b/.github/workflows/terraform-apply.yaml
@@ -27,6 +27,15 @@ jobs:
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
+      - name: Get PR number from commit
+        id: get_pr
+        run: |
+          PR_NUMBER=$(echo "${{ github.event.head_commit.message }}" | grep -oP "(?<=#)[0-9]+" | head -n 1)
+          if [[ -z "$PR_NUMBER" ]]; then
+            echo "Could not extract PR number from commit message."
+            exit 1
+          fi
+          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
       - name: Download Terraform Plan from Azure
         uses: azure/cli@v1
         with:
@@ -34,7 +43,7 @@ jobs:
             az storage blob download \
               --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
               --container-name tfplans \
-              --name pr-${{ github.event.pull_request.number }}/plan.tfplan \
+              --name pr-${{ env.PR_NUMBER }}/plan.tfplan \
               --file terraform-patterns/standard/plan.tfplan \
               --auth-mode login
       - name: Terraform Init
